Update patch set 1
Patch Set 1: Verified-1

FAILED: out/soong/.intermediates/external/libese/tools/ese_relay/ese-relay-fake/darwin_x86_64/obj/external/libese/tools/ese_relay/ese_relay.o
 prebuilts/clang/host/darwin-x86/clang-3688880/bin/clang -c -Isystem/core/include -Isystem/media/audio/include -Ihardware/libhardware/include -Ihardware/libhardware_legacy/include -Ihardware/ril/include -Ilibnativehelper/include -Iframeworks/native/include -Iframeworks/native/opengl/include -isystem frameworks/av/include  -Ilibnativehelper/include/nativehelper -Iexternal/libese/tools/ese_relay  -fno-exceptions -Wno-multichar -fPIC -funwind-tables -D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS -O2 -g -fno-strict-aliasing -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -DMACOSX_DEPLOYMENT_TARGET=10.8 -integrated-as -fstack-protector-strong -m64 -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -DNDEBUG -UDEBUG -D__compiler_offsetof=__builtin_offsetof -Werror=int-conversion -Wno-reserved-id-macro -Wno-format-pedantic -Wno-unused-command-line-argument -fcolor-diagnostics -Wno-expansion-to-defined   -Isystem/core/liblog/include -Iexternal/libese/libese/include -Iexternal/libcxx/include -Iexternal/libcxxabi/include -target x86_64-apple-darwin  -fpie -D_USING_LIBCXX -std=gnu99  -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=address-of-temporary -Werror=return-type -MD -MF out/soong/.intermediates/external/libese/tools/ese_relay/ese-relay-fake/darwin_x86_64/obj/external/libese/tools/ese_relay/ese_relay.o.d -o out/soong/.intermediates/external/libese/tools/ese_relay/ese-relay-fake/darwin_x86_64/obj/external/libese/tools/ese_relay/ese_relay.o external/libese/tools/ese_relay/ese_relay.c
  external/libese/tools/ese_relay/ese_relay.c:21:10: fatal error: 'linux/un.h' file not found
  #include <linux/un.h>
         ^~~~~~~~~~~~
  1 error generated.

Patch-set: 1
Reviewer: Gerrit User 1074628 <1074628@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Verified=-1